__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/rtdetrv2_googlenet


RTDETR:
  backbone: TimmModel


TimmModel:
  name: focalnet_small_lrf
  pretrained: True




HybridEncoder:
  # intra
  in_channels: [192,384,768]
  hidden_dim: 256
  expansion: 0.5



RTDETRTransformerv2:
  num_layers: 3
  num_points: [4, 4, 4]
  cross_attn_method: discrete



optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000005
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

