__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/rtdetrv2_googlenet


RTDETR:
  backbone: TorchVisionModel


TorchVisionModel:
    name: convnext_small
    return_layers: ['2','4','6']
    weights: DEFAULT




HybridEncoder:
  # intra
  in_channels: [192, 384,768]
  hidden_dim: 512
  dim_feedforward: 2048
  num_encoder_layers: 2


RTDETRTransformerv2:
  feat_channels: [512, 512, 512]



optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000005
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

