__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


tuning: https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetrv2_r18vd_120e_coco.pth

output_dir: ./output/vgg16_fr18

RTDETR:
  backbone: TorchVisionModel


TorchVisionModel:
    name: vgg16
    return_layers: ['22','29','30']
    weights: DEFAULT


HybridEncoder:
  in_channels: [512, 512,512]
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformerv2:
  num_layers: 3
  num_points: [4, 4, 4]
  cross_attn_method: discrete


epoches: 26

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 23
  collate_fn:
    scales: ~