__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


tuning: https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetrv2_r18vd_120e_coco.pth

output_dir: ./output/weapons_mobilenet

RTDETR:
  backbone: TorchVisionModel


TorchVisionModel:
    name: mobilenet_v3_large
    return_layers: ['6','11','15']
    weights: DEFAULT


HybridEncoder:
  in_channels: [40, 112, 160]
  hidden_dim: 160
  expansion: 0.5



RTDETRTransformerv2:
  feat_channels: [160, 160, 160]
  feat_strides: [8, 16, 32]
  hidden_dim: 160
  num_layers: 3




epoches: 30



