__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/weapons_hgnetL


RTDETR:
  backbone: HGNetv2

HGNetv2:
  name: 'L'
  return_idx: [1, 2, 3]
  freeze_at: 0
  freeze_norm: True
  pretrained: True

epoches: 30



