__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


tuning: https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetrv2_r18vd_120e_coco.pth

output_dir: ./output/weapons_convnet

TorchVisionModel:
    name: convnext_small
    return_layers: ['2','4','6']
    weights: DEFAULT


HybridEncoder:
  # intra
  in_channels: [512, 1024, 2048]
  hidden_dim: 256
  expansion: 0.5




RTDETRTransformerv2:
  num_layers: 3


epoches: 30



