__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


tuning: https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetrv2_r18vd_120e_coco.pth

output_dir: ./output/weapons_efficient_freeze

RTDETR:
  backbone: TorchVisionModel

TorchVisionModel:
    name: efficientnet_v2_s
    return_layers: ['3','4','6']
    weights: DEFAULT


HybridEncoder:
  in_channels: [64, 128,256]
  hidden_dim: 128
  expansion: 0.5

RTDETRTransformerv2:
  feat_channels: [128, 128, 128]

epoches: 30



